"""rivaldefs: direction and implementation robustness of disagreement between rival rules."""

from ._bounds import DeltaBounds, count_bounds, delta_bounds, discordance_bounds
from ._direction import (
    E0_EDGES,
    NOT_RESOLVED,
    RATIO_EDGES,
    RESOLVED,
    OCRecord,
    band,
    cell,
    cells_for,
    nesting_label,
    orientation_status,
    qualifying_cells,
    ratio_of,
)
from ._grid import Grid, Ladder, gram, grid, grid_from_gram, ladder, scale_h
from ._pair import (
    A_SMALLER,
    B_SMALLER,
    EQUAL,
    TIE_RTOL,
    PairTable,
    h_delta_interval,
    pair_table,
)
from ._resample import (
    Interval,
    PairResult,
    Resampled,
    RulePair,
    RulePairResult,
    bootstrap,
    replicate_weights,
    summarize,
)
from ._rules import (
    DISTINCT,
    INDEPENDENT,
    Rule,
    RuleComparison,
    compare_rules,
    d_within,
    factor_balanced,
    reference_weighted,
)

__version__ = "0.1.0"

__all__ = [
    "A_SMALLER",
    "B_SMALLER",
    "DISTINCT",
    "E0_EDGES",
    "EQUAL",
    "INDEPENDENT",
    "NOT_RESOLVED",
    "RATIO_EDGES",
    "RESOLVED",
    "TIE_RTOL",
    "DeltaBounds",
    "Grid",
    "Interval",
    "Ladder",
    "OCRecord",
    "PairResult",
    "PairTable",
    "Resampled",
    "Rule",
    "RuleComparison",
    "RulePair",
    "RulePairResult",
    "band",
    "bootstrap",
    "cell",
    "cells_for",
    "compare_rules",
    "count_bounds",
    "d_within",
    "delta_bounds",
    "discordance_bounds",
    "factor_balanced",
    "gram",
    "grid",
    "grid_from_gram",
    "h_delta_interval",
    "ladder",
    "nesting_label",
    "orientation_status",
    "pair_table",
    "qualifying_cells",
    "ratio_of",
    "reference_weighted",
    "replicate_weights",
    "scale_h",
    "summarize",
]
